[[params.plugins.css]]
link = "plugins/font-awesome/fontawesome.css"
[[params.plugins.css]]
link = "plugins/font-awesome/brands.css"
[[params.plugins.css]]
link = "plugins/font-awesome/solid.css"
[[params.plugins.js]]
link = "plugins/jquery/jquery.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.js"
[[params.plugins.js]]
link = "plugins/search/fuse.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[[params.plugins.js]]
link = "plugins/webfont-loader/webfont-loader-2.js"
[params.variables]
black = "#000"
body_color = "#FFF"
border_color = "#E1E1E1"
color_primary = "#FFBE17"
font_icon = "Font Awesome 5 Free"
font_primary = "Raleway:wght@400"
font_primary_type = "sans-serif"
font_scale = "1.3"
font_secondary = "Merriweather Sans:wght@400;700"
font_secondary_type = "sans-serif"
font_size = "16px"
light = "#f2f2f2"
text_color = "#555"
text_dark = "#222"
text_light = "#999"
white = "#FFF"
