############# English navigation ##############

# main menu
[[main]]
name = "Start"
url = ""
weight = 1

[[main]]
name = "Om"
url = "#"
weight = 3
hasChildren = true

  [[main]]
  parent = "Om"
  name = "Föreningen"
  url = "about/"
  weight = 1

  [[main]]
  parent = "Om"
  name = "Vaddå Turf?"
  url = "about/"
  weight = 2

[[main]]
name = "Kontakt"
url = "contact/"
weight = 2

[[main]]
name = "Mer"
url = "#"
weight = 4
hasChildren = true

  [[main]]
  parent = "Mer"
  name = "Event"
  url = "event/"
  weight = 1
  
  [[main]]
  parent = "Mer"
  name = "Västerbottens Turf-klassiker"
  url = "klassiker/"
  weight = 2
  
  [[main]]
  parent = "Mer"
  name = "Vandringspokalen"
  url = "vandringspokal/"
  weight = 3
  
  [[main]]
  parent = "Mer"
  name = "Profilkläder"
  url = "profilklader/"
  weight = 4

# footer menu
[[footer]]
name = "Start"
url = "/"
weight = 1

[[footer]]
name = "Om föreningen"
url = "about/"
weight = 2

[[footer]]
name = "Kontakt"
url = "contact/"
weight = 3

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 4
