############# English navigation ##############

# main menu
[[main]]
name = "Start"
url = ""
weight = 1

[[main]]
name = "Om föreningen"
url = "about/"
weight = 2

[[main]]
name = "Vad är Turf?"
url = "contact/"
weight = 3

[[main]]
name = "Kontakt"
url = "contact/"
weight = 4

[[main]]
name = "Västerbottens Turf-klassiker"
url = "klassiker/"
weight = 5

[[main]]
name = "Vandringspokalen"
url = "vandringspokal/"
weight = 6

[[main]]
name = "Event"
url = "#"
weight = 7
hasChildren = true

  [[main]]
  parent = "Event"
  name = "Winter Classic"
  url = "winter-classic/"
  weight = 1

  [[main]]
  parent = "Event"
  name = "Midnight Classic"
  url = "midnight-classic/"
  weight = 2

[[main]]
name = "Profilkläder"
url = "profilklader/"
weight = 6

# footer menu
[[footer]]
name = "Start"
url = "/"
weight = 1

[[footer]]
name = "Om föreningen"
url = "about/"
weight = 2

[[footer]]
name = "Kontakt"
url = "contact/"
weight = 3

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 4
