about_widget_content = "Föreningen Turf Västerbotten är en ideell förening som är religiöst och politiskt obunden. Föreningens syfte är att organisera och sammanhålla medlemmar som utövar sporten Turf inom Västerbottens län (Region Västerbotten). Turf Västerbotten grundades den 4 maj 2019."
address = "Västerbotten"
author = "Turf Västerbotten"
contact_form_action = "#"
copyright = "Föreningen Turf Västerbotten"
custom_script = ""
description = "This is meta description"
email = "info@turfvasterbotten.se"
favicon = "images/favicon.png"
featured_post_title = "Featured Post"
footer_content = "Föreningen för turfare i Västerbotten"
image = "images/logo.png"
logo = "images/logo.png"
logo_text = "Turf Västerbotten"
logo_width = "200x"
mainSections = ["blog"]
mobile = ""
navbar_fixed = false
recent_post_title = "Recent Post"
search = true
[advertisement]
image = "images/promotion.png"
link = "https://gethugothemes.com/"
[banner]
background_image = "/images/banner-bg-shape.svg"
button_label = "Om föreningen"
button_link = "about/"
content = "Föreningen för turfare i Västerbotten"
enable = true
image = "images/banner.jpg"
title_large = "Välkommen **!**"
title_small = "till Turf Västerbotten"
[cookies]
button = "I Accept"
content = "This site uses cookies. By continuing to use this website, you agree to their use."
enable = false
expire_days = 2
[preloader]
enable = false
preloader = ""
[subscription]
enable = false
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074"
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074"
[widgets]
sidebar = ["about", "categories", "recent-post", "newsletter"]
[[social]]
icon = "fab fa-facebook"
link = "#"
title = "facebook"
[[social]]
icon = "fab fa-instagram"
link = "#"
title = "instagram"
